Updated dependencies (including pyo3 0.18) and using new workflows
HQSquantumsimulations/qoqo_aqt pull request #103
Opened 2023-02-23 16:55 UTC by kbarkhqs

2023-02-25 09:05 UTC, mlodi-hqs requested changes
The `pyproject.toml` hasn't been updated (both package and maturin version numbers). Beside that, it looks good.

2023-02-27 10:47 UTC, kbarkhqs commented on qoqo_aqt/Cargo.toml
> +roqoqo = {version="1.2.5"}
Changed to 1.1 and 1.2

2023-02-27 10:47 UTC, kbarkhqs commented on roqoqo-aqt/Cargo.toml
> +qoqo_calculator = { version="1.1.1"}
Changed as above

2023-02-27 10:53 UTC, kbarkhqs commented on CHANGELOG.md
> +* Updated to pyo3 0.18
Fixed

2023-02-27 12:09 UTC, mlodi-hqs approved these changes

2023-02-27 12:54 UTC, merged